### ISSUE TITLE
没有找到_pretrain/val_webvid2.5m.yaml

### ISSUE THREAD

**Issue by qianyunw** [tsujuifu/pytorch_empirical-mvm#1]
Hi

非常棒的工作，复现pretrain任务时，提示没有找到yaml_file:_pretrain/val_webvid2.5m.yaml，请问这个文件在哪里呢，非常感谢

**Comment by tsujuifu** [comment]
Hi @qianyunw 

You can download it [here](https://drive.google.com/file/d/1VvHNfUF_493LDc7zL-zLEniKRyOLGU_J) in the [_pretrain folder](https://drive.google.com/drive/u/1/folders/1AR1NooeNVhx5o1Lt5oGLW7z_Ogu-ezgm).

**Comment by qianyunw** [comment]
谢谢，王倩芸已收到。
