### ISSUE TITLE
Test data discrepancy

### ISSUE THREAD

**Issue by avinashsai** [tsujuifu/pytorch_empirical-mvm#2]
Hi,

Congrats on the amazing work!! For the DiDeMo video retrieval, the test data used has 913 samples where as CLIP4Clip has 1003 samples. Is it the value reported in the paper based on 913 or 1003?

Thank you.

**Comment by tsujuifu** [comment]
Hi, 

Our used DiDeMo-Retrieval is as [here](https://drive.google.com/uc?id=1rzD_0242-dFwF7zywynE8wexb-DDPVrF), which contains 8245 for training, 1053 for validation, and 979 for testing.
