### ISSUE TITLE
Missing training datasets and checkpoint of MSRVTT-MC

### ISSUE THREAD

**Issue by raymin0223** [tsujuifu/pytorch_empirical-mvm#5]
Hi @tsujuifu,
Thanks for your great work and tidy github for future works!

I found that MSRVTT-MC _train_- and _val_-datasets are missed in google drive, and also same for the checkpoint.
It would be appreciated if you upload those things, thanks.

**Comment by tsujuifu** [comment]
For MC, the learning scenario is similar to retrieval (text-video alignment).

MSRVTT-MC shares the same train/val data as MSRVTT-Retrieval.
The trained checkpoint is also identical.

**Comment by raymin0223** [comment]
Oh I see, thank you very much for your reply!
