### ISSUE TITLE
My dataset

### ISSUE THREAD

**Issue by anas2908** [tsujuifu/pytorch_empirical-mvm#8]
Hi sir, 
I want to run my dataset on your model, can you give some information more about your dataset, i am not able to figure out what the video_id and id fields are, and any **code related to preprocessing the dataset** will be helpful. 
Thankyou

**Comment by tsujuifu** [comment]
Here is an example of [data pre-processing](https://github.com/tsujuifu/pytorch_violet?tab=readme-ov-file#data-preprocessing), including **making the tsv file from videos**.
